- app/User.php
- routes/web.php
E-Mail verification activated, but not used, at the moment
> activated e-mail verification

- resources/views/layouts/frontend.blade.php
- resources/views/welcome.blade.php
added a frontend, based on adminlte
> added frontend

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/CompanyChangeController.php
resolves a bug with redirect after login
> bugfix: login redirect

- app/Http/Controllers/Auth/LoginController.php
> bugfix: login bugfix

- resources/views/layouts/backend.blade.php
- resources/views/layouts/language-dropdown.blade.php
> bugfix: backend menu header

- package-lock.json
- package.json
- resources/views/course/create.blade.php
- webpack.mix.js
small bugfix for bootstrap-switch
> bugfix: bootstrap-switch

- resources/views/course/old.blade.php
bugfix: forgot hashids for old course overview
> bugfix: hashids

- app/Http/Controllers/CompanyChangeController.php
- app/Http/Controllers/InvitationController.php
- resources/views/emails/trainer-invite.blade.php
- resources/views/invitation/index.blade.php
bugfix: bug trainer invitation caused of the hashid
> bugfix: trainer invitation

- package-lock.json
- package.json
> update: adminlte

- package-lock.json
- package.json
fast security fix to update "kind-of"
> security fix: kind-of

- package.json
> security update: minimist

- composer.json
- composer.lock
- resources/views/auth/register.blade.php
- routes/web.php
added spatie/laravel-honeypot as spam protection.
Revolves #19 and #290
> added spatie/laravel-honeypot

- database/seeds/CourseTypesSeeder.php
- resources/lang/de.json
- resources/lang/en.json
added first aid course according to § 68 FEV
closes #97
> added first aid course § 68 FEV

- resources/views/auth/login.blade.php
> added honeypot to login

- app/Http/Controllers/CompanyController.php
- app/Http/Controllers/CourseController.php
- app/Http/Controllers/CourseDayController.php
- app/Http/Controllers/CourseTypesController.php
- app/Http/Controllers/PermissionController.php
- app/Http/Controllers/TrainerController.php
- composer.json
- composer.lock
- config/laratrust.php
- database/seeds/LaratrustSeeder.php
- resources/views/course/create.blade.php
- resources/views/permission/edit.blade.php
> Laratrust update

- resources/views/course/show.blade.php
> laratrust update adaptation

- resources/css/sign.css
- webpack.mix.js
bugfix: the sign.css for signature field was missing
> bugfix: sign.css

- CHANGELOG.md
- resources/lang/de.json
- resources/lang/en.json
- resources/views/permission/edit.blade.php
Permission *view course* to *view all courses* changed
> "view course" changed

- CHANGELOG.md
- app/Http/Controllers/CourseController.php
bugfix replaces */* with *-* in the internal number
> bugfix internal number

- config/laratrust.php
Some changes after a laratrust update
> post laratrust update

- CHANGELOG.md
- app/Http/Controllers/CompanyChangeController.php
- app/Http/Controllers/CompanyController.php
two bugfixes for creating and changing a company
> bugfix: create & change company

- CHANGELOG.md
- package-lock.json
- resources/lang/de.json
- resources/lang/en.json
- resources/views/company/create.blade.php
- resources/views/company/edit.blade.php
- resources/views/course/create.blade.php
- resources/views/coursetype/index.blade.php
- resources/views/permission/edit.blade.php
- resources/views/trainer/create.blade.php
bugfix: prevent double submit a form
> bugfix: form double submit prevent

- CHANGELOG.md
- app/Http/Controllers/CourseController.php
- resources/lang/de.json
- resources/lang/en.json
- resources/views/course/create.blade.php
added a function to automaticly an internal number
> added generate internal number

- CHANGELOG.md
- resources/views/course/create.blade.php
bugfix: don't show inactive trainer
> bugfix: don't show inactive trainer
